"""user group relation created

Revision ID: f961d521f1bd
Revises: 45ba27931e95
Create Date: 2025-06-09 16:15:17.367654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f961d521f1bd'
down_revision: Union[str, None] = '45ba27931e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trades', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'user_group_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_group_association', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group_association', type_='foreignkey')
    op.drop_constraint(None, 'user_group_association', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    # ### end Alembic commands ###
