"""Move group ownership from Asset to Trade

Revision ID: 45ba27931e95
Revises: cccd2383833a
Create Date: 2025-06-09 15:00:02.199538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45ba27931e95'
down_revision: Union[str, None] = 'cccd2383833a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_table('user_group_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.add_column('trades', sa.Column('group_id', sa.Integer(), nullable=False))
    op.alter_column('trades', 'asset_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_trades_group_id'), 'trades', ['group_id'], unique=False)
    op.create_foreign_key(None, 'trades', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_group_id'), table_name='trades')
    op.alter_column('trades', 'asset_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('trades', 'group_id')
    op.drop_table('user_group_association')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
