"""Add currency to trades table

Revision ID: 4f5cb281ab2d
Revises: 8af28d08dfcc
Create Date: 2025-06-05 20:08:05.922106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5cb281ab2d'
down_revision: Union[str, None] = '8af28d08dfcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False))
    op.create_foreign_key(None, 'trades', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'currency')
    # ### end Alembic commands ###
