"""Implement scoped group roles via association object

Revision ID: b46451958cb3
Revises: f961d521f1bd
Create Date: 2025-06-09 18:56:21.955624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46451958cb3'
down_revision: Union[str, None] = 'f961d521f1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trades', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'groups', ['group_id'], ['id'])
    op.add_column('user_group_association', sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='groupmemberrole'), nullable=False))
    op.create_foreign_key(None, 'user_group_association', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'user_group_association', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group_association', type_='foreignkey')
    op.drop_constraint(None, 'user_group_association', type_='foreignkey')
    op.drop_column('user_group_association', 'role')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    # ### end Alembic commands ###
