from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from . import orm_models
from datetime import datetime

async def get_asset_by_id(db: AsyncSession, asset_id: int):
    """Fetches a single asset by its ID."""
    query = select(orm_models.Asset).where(orm_models.Asset.id == asset_id)
    result = await db.execute(query)
    return result.scalar_one_or_none()

async def get_asset_by_symbol(db: AsyncSession, symbol: str):
    """Fetches a single asset by its symbol."""
    query = select(orm_models.Asset).where(orm_models.Asset.symbol == symbol)
    result = await db.execute(query)
    return result.scalar_one_or_none()

async def get_all_assets(db: AsyncSession, skip: int = 0, limit: int = 100):
    """Fetches all assets with pagination."""
    query = select(orm_models.Asset).offset(skip).limit(limit)
    result = await db.execute(query)
    return result.scalars().all()

async def get_asset_by_symbol_or_id(db: AsyncSession, symbol: str = None, asset_id: int = None):
    """Fetches an asset by either its symbol or ID."""
    if symbol:
        return await get_asset_by_symbol(db, symbol)
    elif asset_id:
        return await get_asset_by_id(db, asset_id)
    else:
        raise ValueError("Either 'symbol' or 'asset_id' must be provided.")

async def create_asset(db: AsyncSession, asset_data: dict):
    """Creates a new asset record in the database."""
    # Create an instance of the SQLAlchemy ORM model
    db_asset = orm_models.Asset(**asset_data)
    
    # Add the new object to the session
    db.add(db_asset)
    
    # Commit the changes to the database
    await db.commit()
    
    # Refresh the object to get the new ID generated by the database
    await db.refresh(db_asset)
    
    return db_asset

async def update_asset(db: AsyncSession, asset_id: int, asset_data: dict):
    """Updates an existing asset record in the database."""
    db_asset = await get_asset_by_id(db, asset_id)
    if not db_asset:
        return None
    
    for key, value in asset_data.items():
        setattr(db_asset, key, value)
    
    await db.commit()
    await db.refresh(db_asset)
    
    return db_asset

async def update_asset_price(db: AsyncSession, asset: orm_models.Asset, new_price: float):
    """
    Updates the price and timestamp for a given asset record.
    """
    asset.current_price = new_price
    asset.price_last_updated = datetime.utcnow()
    
    # The session already knows about the 'asset' object,
    # so we just need to commit the changes.
    await db.commit()
    
    # Refresh the instance to get the latest data from the DB, like the 'updated_at' timestamp
    await db.refresh(asset)
    
    return asset

async def create_trade(db: AsyncSession, asset_id: int, trade_data: dict):
    """Creates a new trade record for a given asset."""
    db_trade = orm_models.Trade(
        **trade_data,
        asset_id=asset_id
    )
    db.add(db_trade)
    await db.commit()
    await db.refresh(db_trade)
    return db_trade

async def get_trades_by_asset_id(db: AsyncSession, asset_id: int):
    """Fetches all trades for a specific asset ID."""
    query = select(orm_models.Trade).where(orm_models.Trade.asset_id == asset_id)
    result = await db.execute(query)
    return result.scalars().all()

async def get_all_trades(db: AsyncSession, skip: int = 0, limit: int = 100):
    """Fetches all trades with pagination."""
    query = select(orm_models.Trade).offset(skip).limit(limit)
    result = await db.execute(query)
    return result.scalars().all()

async def get_trades_before_date(db: AsyncSession, end_date: datetime):
    """Fetches all trades that occurred before a specific date."""
    query = select(orm_models.Trade).where(orm_models.Trade.trade_date < end_date)
    result = await db.execute(query)
    return result.scalars().all()

async def get_trades_in_date_range(db: AsyncSession, start_date: datetime, end_date: datetime):
    """Fetches all trades within a specific date range."""
    query = select(orm_models.Trade).where(
        orm_models.Trade.trade_date >= start_date,
        orm_models.Trade.trade_date <= end_date
    )
    result = await db.execute(query)
    return result.scalars().all()